runtime: java11
instance_class: F2
#service: logtest
service: default
automatic_scaling:
  max_instances: 1
# No need for an entrypoint, the generated default does java -jar xxx.jar
inbound_services:
  - warmup
entrypoint:
  java -jar log-error-too-slow-1.0.0-SNAPSHOT-runner.jar
